spring:
  datasource:
    hikari:
      username: springboot
      password: kkk
      jdbc-url: jdbc:oracle:thin:@localhost:1521:XE
      driver-class-name: oracle.jdbc.OracleDriver
      validationTimeout: 10000
      maximumPoolSize: 50
      leakDetectionThreshold: 1
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    database: ORACLE
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: validate
      lock:
        time: 50000
      jdbc:
        batch_size: 40
server:
  port: 18080
  servlet:
    context-path: /kotoo
  undertow:
    io-threads: 32
    worker-threads: 256

undertow:
  idle:
    timeout: 300000
  norequest:
    timeout: 300000


work:
  thread:
    pool:
      size: 100

db:
  encrypt:
    enable: true
    password: true

management:
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: shutdown, health
      base-path: /
