spring:
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: PT1H
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database: h2
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:store_manager;MODE=ORACLE;DB_CLOSE_DELAY=-1"
    username: sa
    password:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: H2_DB
#  datasource:
#    hikari:
#      username: springboot
#      password: springboot
#      jdbc-url: jdbc:oracle:thin:@localhost:1521:XE
#      driver-class-name: oracle.jdbc.OracleDriver
#      validationTimeout: 10000
#      maximumPoolSize: 50
#      leakDetectionThreshold: 1
#  jpa:
#    database-platform: org.hibernate.dialect.Oracle10gDialect
#    database: ORACLE
#    show-sql: true
#    generate-ddl: true
#    properties:
#      hibernate:
#        format_sql: true
#        use_sql_comments: true
#    hibernate:
#      naming:
#        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
#        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
#      ddl-auto: validate
server:
  port: 18080
  servlet:
    context-path: /kotto
  undertow:
    io-threads: 32
    worker-threads: 256

management:
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: shutdown, health
      base-path: /
enc:
  key: oingisprettyintheworld1234567890
